import { EventEmitter } from '@angular/core';
export declare class Ng2TagsInput {
    placeholder: string;
    model: string[];
    delimiterCode: string;
    addOnBlur: boolean;
    addOnEnter: boolean;
    addOnPaste: boolean;
    allowedTagsPattern: RegExp;
    isFocussed: any;
    tagsChanged: EventEmitter<any>;
    tagsAdded: EventEmitter<any>;
    tagRemoved: EventEmitter<any>;
    tagsList: string[];
    inputValue: string;
    delimiter: number;
    selectedTag: number;
    constructor();
    ngOnInit(): void;
    inputChanged(event: any): void;
    inputBlurred(event: any): void;
    inputFocused(event: any): void;
    inputPaste(event: any): void;
    private _splitString(tagString);
    private _isTagValid(tagString);
    private _addTags(tags);
    private _removeTag(tagIndexToRemove);
    private _handleBackspace();
    private _resetSelected();
    private _resetInput();
}
